package me.lokka.jz.dao;

import java.util.List;
import me.lokka.jz.bean.AccountSystem;
import me.lokka.jz.bean.AccountSystemExample;
import org.apache.ibatis.annotations.Param;

public interface AccountSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_account_system
     *
     * @mbg.generated Thu Jun 11 14:38:05 GMT+08:00 2020
     */
    long countByExample(AccountSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_account_system
     *
     * @mbg.generated Thu Jun 11 14:38:05 GMT+08:00 2020
     */
    int deleteByExample(AccountSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_account_system
     *
     * @mbg.generated Thu Jun 11 14:38:05 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_account_system
     *
     * @mbg.generated Thu Jun 11 14:38:05 GMT+08:00 2020
     */
    int insert(AccountSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_account_system
     *
     * @mbg.generated Thu Jun 11 14:38:05 GMT+08:00 2020
     */
    int insertSelective(AccountSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_account_system
     *
     * @mbg.generated Thu Jun 11 14:38:05 GMT+08:00 2020
     */
    List<AccountSystem> selectByExample(AccountSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_account_system
     *
     * @mbg.generated Thu Jun 11 14:38:05 GMT+08:00 2020
     */
    AccountSystem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_account_system
     *
     * @mbg.generated Thu Jun 11 14:38:05 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") AccountSystem record, @Param("example") AccountSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_account_system
     *
     * @mbg.generated Thu Jun 11 14:38:05 GMT+08:00 2020
     */
    int updateByExample(@Param("record") AccountSystem record, @Param("example") AccountSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_account_system
     *
     * @mbg.generated Thu Jun 11 14:38:05 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(AccountSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_account_system
     *
     * @mbg.generated Thu Jun 11 14:38:05 GMT+08:00 2020
     */
    int updateByPrimaryKey(AccountSystem record);
}