package me.lokka.jz.dao;

import java.util.List;
import me.lokka.jz.bean.Privilege;
import me.lokka.jz.bean.PrivilegeExample;
import org.apache.ibatis.annotations.Param;

public interface PrivilegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_privilege
     *
     * @mbg.generated Thu Jun 11 14:38:05 GMT+08:00 2020
     */
    long countByExample(PrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_privilege
     *
     * @mbg.generated Thu Jun 11 14:38:05 GMT+08:00 2020
     */
    int deleteByExample(PrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_privilege
     *
     * @mbg.generated Thu Jun 11 14:38:05 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_privilege
     *
     * @mbg.generated Thu Jun 11 14:38:05 GMT+08:00 2020
     */
    int insert(Privilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_privilege
     *
     * @mbg.generated Thu Jun 11 14:38:05 GMT+08:00 2020
     */
    int insertSelective(Privilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_privilege
     *
     * @mbg.generated Thu Jun 11 14:38:05 GMT+08:00 2020
     */
    List<Privilege> selectByExample(PrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_privilege
     *
     * @mbg.generated Thu Jun 11 14:38:05 GMT+08:00 2020
     */
    Privilege selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_privilege
     *
     * @mbg.generated Thu Jun 11 14:38:05 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") Privilege record, @Param("example") PrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_privilege
     *
     * @mbg.generated Thu Jun 11 14:38:05 GMT+08:00 2020
     */
    int updateByExample(@Param("record") Privilege record, @Param("example") PrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_privilege
     *
     * @mbg.generated Thu Jun 11 14:38:05 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(Privilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_privilege
     *
     * @mbg.generated Thu Jun 11 14:38:05 GMT+08:00 2020
     */
    int updateByPrimaryKey(Privilege record);
}